config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :computers
  # Defines the root path route ("/")
  root "computers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/computer.rb
class Computer < ApplicationRecord
    paginates_per 10

    def self.ransackable_attributes(auth_object = nil)
        %w[name brand description price]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_computer, only: %i[show edit update destroy]

    def index
      # Tìm kiếm với Ransack
      @q = Computer.ransack(params[:q])
      @computers = @q.result.page(params[:page]) # Phân trang với Kaminari
    end

    def show
    end

    def new
      @computer = Computer.new
    end

    def create
      @computer = Computer.new(computer_params)
      if @computer.save
        redirect_to computers_path, notice: "Computer was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @computer.update(computer_params)
        redirect_to computers_path, notice: "Computer was successfully updated."
      else
        render :edit
      end
    end

    def destroy
      @computer.destroy
      redirect_to computers_path, notice: "Computer was successfully deleted."
    end

    private

    def set_computer
      @computer = Computer.find(params[:id])
    end

    def computer_params
      params.require(:computer).permit(:name, :brand, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= form_with(model: @computer, local: true) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :brand %>
      <%= form.text_field :brand %>
    </div>

    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :price %>
      <%= form.number_field :price, step: 0.01 %>
    </div>

    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/computers/edit.html.erb
<h1>Edit Computer</h1>

<%= form_with(model: @computer, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div>
    <%= form.submit "Update Computer" %>
  </div>
<% end %>

app/views/computers/index.html.erb
<h1>Computers</h1>

<%= search_form_for @q do |f| %>
    <%= f.label :name_cont, "Search by name" %>
    <%= f.text_field :name_cont %>
    <%= f.submit "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Description</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td><%= computer.name %></td>
        <td><%= computer.brand %></td>
        <td><%= computer.description %></td>
        <td><%= number_to_currency(computer.price) %></td>
        <td>
          <%= link_to "Edit", edit_computer_path(computer) %> |
        <%= link_to "delete", computer, data: { "turbo-method": :delete, turbo_confirm: "You sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @computers %>

<%= link_to "Add new computer", new_computer_path %>

app/views/computers/new.html.erb
<h1>New Computer</h1>

<%= form_with(model: @computer, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div>
    <%= form.submit "Create Computer" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComputerManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <nav>
      <% if user_signed_in? %>
        <p>Welcome, <%= current_user.email %>!</p>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %>
      <% else %>
        <%= link_to "Login", new_user_session_path %> |
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </nav>
  </body>
</html>